// Copyright (c) 2015 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(m){var f,b={_breaker:{},_start:null,each:function(){var a,c=function(c,e){return c===b._breaker||e&&b.elapsed()>a};return function(d,e,g){var k,l;l=b.type(d);if(1===arguments.length)a=arguments[0];else if(g=b.extend({timeout:!1},g),"object"===l&&d.hasOwnProperty)for(k in d){if(d.hasOwnProperty(k)&&c(e(d[k],k),g.timeout))break}else if(d){k=0;for(l=d.length;k<l&&!c(e(d[k],k),g.timeout);k++);}}}(),extend:function(a){var c,b,e,g,k=arguments.length;a=a||{};for(b=1;b<k;b++)if(g=arguments[b],void 0!==
g&&null!==g)for(e in g)c=g[e],a!==c&&void 0!==c&&(a[e]=c);return a},noop:function(){},type:function(){var a=function(a,b){try{return("function"===typeof window[b]||"object"===typeof window[b])&&a instanceof window[b]}catch(e){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?
"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var d="array"===b.type(a)?[]:{};b.each(a,function(a,g){c(a,g)&&("array"===b.type(d)?d.push(a):d[g]=a)});return d},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,b){return(c=a[c])?c.split(b||" "):[]},batchable:function(a,c){c=c||b.noop;var d=
function(){return b.extend({batch:!0,timeout:100},c())},e=b.traits.cors&&b.traits.json,g=[],k=null,l=function(){null!==k&&(clearTimeout(k),k=null);1===g.length?a.apply(null,g[0].arguments):1<g.length&&a.apply(null,g);g=[]},f=function(){g.push({arguments:b.toArray(arguments),batch:!0});!e||!d().batch?l():null===k&&(k=setTimeout(b.entryPoint(b.bind(function(){l()},this)),d().timeout))};b.extend(f,{flush:l,now:a});return f},batchArgs:function(a,c){return b.map(a,function(a){return void 0===c?a.arguments:
a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(a){return"object"===b.type(a)&&a.batch&&"array"===b.type(a.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(e,g,k){if(e){var l=e[c];if(l||void 0!==k)return l||(l=++b),a[l]||(e[c]=l,a[l]={}),void 0!==k&&(a[l][g]=k),"string"===typeof g?a[l][g]:a[l]}}}(),canonicalizeHostname:function(a){"string"===
typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return b.extend({},a)},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===c)return!0;return!1},
cors:function(a,b,d){var e,g=function(){d?d(e.responseText):eval(e.responseText)};e=new window.XMLHttpRequest;e.onreadystatechange=function(){4===e.readyState&&200===e.status&&g()};try{return e.open("POST",a),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),e.withCredentials=!0,e.send(b),!0}catch(k){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var g;a=(e||document).createElement(a);c=c||{};d=d||{};for(g in c)void 0!==c[g]&&
(a[g]=c[g]);b.css(a,d);return a},css:function(a,b){for(var d in b)try{a.style[d]=b[d]}catch(e){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||(e=a.apply(null,arguments),b=!0);return e}}(a)},elapsed:function(){return this._start?(new Date).getTime()-this._start.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},escapeRegExp:function(){var a;
return function(b){a=a||/([.*+?^${}()|[\]\\])/g;return b.replace(a,"\\$1")}}(),eventLink:function(a){var b,d=a.target||a.srcElement;do{try{b=d.nodeType}catch(e){break}if(1===b&&(a=d.tagName.toUpperCase(),"A"===a||"AREA"===a))return d;d=d.parentNode}while(d)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,arguments)}}}(),find:function(a,c,d){var e;b.each(a,
function(a,d){if(c(a,d))return e=a,b._breaker},d);return e},generateNodeFilter:function(){var a=function(a,b){var g,k;b=","+b.join(",")+",";g=0;for(k=a.length;g<k;g++)if(c(a[g],b))return!0;return!1},c=function(a,b){return-1!==b.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,g){g=b.extend({ancestors:!0,self:!0},g);var k=!0,l=!0,f=function(e,g){var k;if(k=!(d.tags.length&&
c(e.nodeName.toLowerCase(),d.tags))){if(k=d.classes.length){k=d.classes;var l=b.attrValues(e,"className");k=a(k,l)}if(k=!k){if(k=d.rels.length)k=d.rels,l=b.attrValues(e,"rel"),k=c(e.nodeName.toLowerCase(),",a,")&&a(k,l);k=!k&&!("function"===b.type(d.custom)&&d.custom(e,g))}}return k},l=!g.self||f(e,!0);if(g.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!f(e,!1)){k=!1;break}return l&&k}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===
a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,g=-Infinity,k=-Infinity,l;for(a=0;a<c;a++)l=b.position(arguments[a]),d=Math.min(d,l.x),e=Math.min(e,l.y),g=Math.max(g,l.x+arguments[a].offsetWidth),k=Math.max(k,l.y+arguments[a].offsetHeight);return{x:d,y:e,w:g-d,h:k-e,x1:d,y1:e,x2:g,y2:k}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c,d){return b.reduce([],a,function(a,b,d){a.push(c(b,d));return a},d)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(d){return!0}},on:function(){var a;return function(c,d,e){var g,k,l;if(1===arguments.length)a=c;else{if(2===arguments.length){if(!a)return;e=d;d=c;c=a}else g=b.toArray(arguments).slice(3,arguments.length);try{k=c["on"+d]}catch(f){}"function"===
typeof k&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=k.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));l=b.entryPoint(function(){if(a.enabled())return e.apply(null,b.toArray(arguments).concat(g||[]))});c.addEventListener?c.addEventListener(d,l,!1):c.attachEvent&&c.attachEvent("on"+d,l)}}}(),position:function(a,c){var d,
e=0,g=0,k=0,l=0;c=c||document;if(!b.isInDom(a))return!1;d=a;do e+=d.offsetLeft,g+=d.offsetTop,d=d.offsetParent;while(d);d=a;do k+=d.scrollLeft,l+=d.scrollTop,d=d.parentNode;while(d&&d!==c.body);return{x:e-k,y:g-l}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(b,d){(null===b||void 0===b)&&delete a[d]});return a},ready:function(){var a=!1,c=[],d=!1,e,g,k,l,f;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",
k,!1);f()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),f())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return f();if(document.addEventListener)document.addEventListener("DOMContentLoaded",k,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",l);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&g()}b.on(window,
"load",f)}};g=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(g),1);return}f()}};f=function(){if(!d){if(!document.body)return setTimeout(b.entryPoint(f),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reduce:function(a,c,d,e){b.each(c,function(b,c){a=d(a,b,c)},e);return a},reformatKeys:function(a){var c,d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&
(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,g=b.attrValues(a,"className");d=0;for(e=g.length;d<e;d++)g[d]===c&&delete g[d];a.className=g.join(" ")}},request:function(a,c,d){var e,g,k,l=b.uniqid("vglnk_"),f=b.toArray(arguments).slice(3,arguments.length),h=function(a,c,d){var e=b.createA(a).protocol;c.length&&(a=b.updateUrl(a,{search:"?"+c}));if(!0===d||!1===d)a=b.updateUrl(a,{protocol:e.replace(/s?:$/,function(){return d?
"s:":":"})});return a};d=b.extend({fn:b.noop,jsonp:!0,"return":!1,ssl:null,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],l=d.fn):"function"===typeof d.fn&&(e=d.fn);"function"===b.type(e)&&(k=b.entryPoint(b.destructing(function(){e.apply(this,b.toArray(arguments).concat(f));window[l]&&(window[l]=void 0)})),null!==d.timeout&&setTimeout(k,d.timeout));!0===d.jsonp&&(window[l]=k,c=b.extend({format:"jsonp",jsonp:l},c));g=b.toQuery(c);return d["return"]?h(a,g,d.ssl):b.traits.cors&&b.cors(h(a,"",
d.ssl),g,d.jsonp?null:k)?!0:b.jsonp(h(a,g,d.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var d,e,g=[];d=0;for(e=a.length;d<e;d++)g[d]=a[d];return g}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},
updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,d){b.contains(a,d)||a.push(d);return a})},withScope:function(){var a=function(a,d,e){if(e.self&&b.contains(d,a))return a;if(e.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(d,a)},{timeout:!0})};return function(c,d,e){var g=b.select(d);e=b.extend({ancestors:!0,descendants:!0,
self:!0},e);return b.all(b.map(c,function(c){var d,f=[];(d=a(c,g,e))?f.push(d):1===c.nodeType&&e.descendants&&b.each(g,function(a){b.contains(b.ancestors(a),c)&&f.push(a)},{timeout:!0});return[c,f]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0})}}()});var r=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};r.amd=!0;(function(a){function b(a,c,d,e){var g,k,l,f,h;(c?c.ownerDocument||c:C)!==A&&I(c);c=c||A;d=d||[];if(!a||"string"!==
typeof a)return d;if(1!==(f=c.nodeType)&&9!==f)return[];if(E&&!e){if(g=qa.exec(a))if(l=g[1])if(9===f)if((k=c.getElementById(l))&&k.parentNode){if(k.id===l)return d.push(k),d}else return d;else{if(c.ownerDocument&&(k=c.ownerDocument.getElementById(l))&&T(c,k)&&k.id===l)return d.push(k),d}else{if(g[2])return J.apply(d,c.getElementsByTagName(a)),d;if((l=g[3])&&w.getElementsByClassName&&c.getElementsByClassName)return J.apply(d,c.getElementsByClassName(l)),d}if(w.qsa&&(!B||!B.test(a))){k=g=x;l=c;h=9===
f&&a;if(1===f&&"object"!==c.nodeName.toLowerCase()){f=U(a);(g=c.getAttribute("id"))?k=g.replace(ra,"\\$&"):c.setAttribute("id",k);k="[id='"+k+"'] ";for(l=f.length;l--;)f[l]=k+m(f[l]);l=ca.test(a)&&p(c.parentNode)||c;h=f.join(",")}if(h)try{return J.apply(d,l.querySelectorAll(h)),d}catch(v){}finally{g||c.removeAttribute("id")}}}return ja(a.replace(X,"$1"),c,d,e)}function d(){function a(c,d){b.push(c+" ")>s.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[x]=!0;return a}
function g(a){var b=A.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function k(a,b){for(var c=a.split("|"),d=a.length;d--;)s.attrHandle[c[d]]=b}function l(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ka)-(~a.sourceIndex||ka);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function f(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function h(a){return function(b){var c=
b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function u(a){return e(function(b){b=+b;return e(function(c,d){for(var e,g=a([],c.length,b),k=g.length;k--;)if(c[e=g[k]])c[e]=!(d[e]=c[e])})})}function p(a){return a&&typeof a.getElementsByTagName!==P&&a}function n(){}function m(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function q(a,b,c){var d=b.dir,e=c&&"parentNode"===d,g=ta++;return b.first?function(b,c,g){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,g)}:
function(b,c,ba){var k,l,f=[D,g];if(ba)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,ba))return!0}else for(;b=b[d];)if(1===b.nodeType||e){l=b[x]||(b[x]={});if((k=l[d])&&k[0]===D&&k[1]===g)return f[2]=k[2];l[d]=f;if(f[2]=a(b,c,ba))return!0}}}function t(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function Q(a,b,c,d,e){for(var g,k=[],l=0,f=a.length,h=null!=b;l<f;l++)if(g=a[l])if(!c||c(g,d,e))k.push(g),h&&b.push(l);return k}function da(a,d,g,k,l,
f){k&&!k[x]&&(k=da(k));l&&!l[x]&&(l=da(l,f));return e(function(e,f,h,v){var p,u,n=[],y=[],ia=f.length,z;if(!(z=e)){z=d||"*";for(var m=h.nodeType?[h]:h,q=[],t=0,s=m.length;t<s;t++)b(z,m[t],q);z=q}z=a&&(e||!d)?Q(z,n,a,h,v):z;m=g?l||(e?a:ia||k)?[]:f:z;g&&g(z,m,h,v);if(k){p=Q(m,y);k(p,[],h,v);for(h=p.length;h--;)if(u=p[h])m[y[h]]=!(z[y[h]]=u)}if(e){if(l||a){if(l){p=[];for(h=m.length;h--;)if(u=m[h])p.push(z[h]=u);l(null,m=[],p,v)}for(h=m.length;h--;)if((u=m[h])&&-1<(p=l?N.call(e,u):n[h]))e[p]=!(f[p]=u)}}else m=
Q(m===f?m.splice(ia,m.length):m),l?l(null,f,m,v):J.apply(f,m)})}function ea(a){var b,c,d,e=a.length,k=s.relative[a[0].type];c=k||s.relative[" "];for(var g=k?1:0,l=q(function(a){return a===b},c,!0),f=q(function(a){return-1<N.call(b,a)},c,!0),h=[function(a,c,d){return!k&&(d||c!==Y)||((b=c).nodeType?l(a,c,d):f(a,c,d))}];g<e;g++)if(c=s.relative[a[g].type])h=[q(t(h),c)];else{c=s.filter[a[g].type].apply(null,a[g].matches);if(c[x]){for(d=++g;d<e&&!s.relative[a[d].type];d++);return da(1<g&&t(h),1<g&&m(a.slice(0,
g-1).concat({value:" "===a[g-2].type?"*":""})).replace(X,"$1"),c,g<d&&ea(a.slice(g,d)),d<e&&ea(a=a.slice(d)),d<e&&m(a))}h.push(c)}return t(h)}function va(a,d){var g=0<d.length,k=0<a.length,l=function(e,l,f,h,v){var p,u,y,n=0,m="0",z=e&&[],M=[],q=Y,t=e||k&&s.find.TAG("*",v),ha=D+=null==q?1:Math.random()||0.1,w=t.length;for(v&&(Y=l!==A&&l);m!==w&&null!=(p=t[m]);m++){if(k&&p){for(u=0;y=a[u++];)if(y(p,l,f)){h.push(p);break}v&&(D=ha)}g&&((p=!y&&p)&&n--,e&&z.push(p))}n+=m;if(g&&m!==n){for(u=0;y=d[u++];)y(z,
M,l,f);if(e){if(0<n)for(;m--;)!z[m]&&!M[m]&&(M[m]=wa.call(h));M=Q(M)}J.apply(h,M);v&&(!e&&0<M.length&&1<n+d.length)&&b.uniqueSort(h)}v&&(D=ha,Y=q);return z};return g?e(l):l}var R,w,s,Z,la,U,fa,ja,Y,K,S,I,A,F,E,B,O,$,T,x="sizzle"+-new Date,C=a.document,D=0,ta=0,ma=d(),na=d(),oa=d(),ga=function(a,b){a===b&&(S=!0);return 0},P="undefined",ka=-2147483648,xa={}.hasOwnProperty,L=[],wa=L.pop,ya=L.push,J=L.push,pa=L.slice,N=L.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},
X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,za=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ba=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ca=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Da=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,aa={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ea=/^(?:input|select|textarea|button)$/i,Fa=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,qa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ca=/[+~]/,ra=/'|\\/g,G=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,H=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{J.apply(L=pa.call(C.childNodes),C.childNodes),L[C.childNodes.length].nodeType}catch(Ga){J={apply:L.length?function(a,b){ya.apply(a,pa.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}w=b.support={};la=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};I=b.setDocument=function(a){var b=a?a.ownerDocument||a:C;a=b.defaultView;if(b===A||9!==b.nodeType||!b.documentElement)return A;A=b;F=b.documentElement;E=!la(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){I()},!1):a.attachEvent&&a.attachEvent("onunload",function(){I()}));w.attributes=g(function(a){a.className="i";return!a.getAttribute("className")});
w.getElementsByTagName=g(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});w.getElementsByClassName=V.test(b.getElementsByClassName)&&g(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});w.getById=g(function(a){F.appendChild(a).id=x;return!b.getElementsByName||!b.getElementsByName(x).length});w.getById?(s.find.ID=function(a,b){if(typeof b.getElementById!==P&&E){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},s.filter.ID=function(a){var b=a.replace(G,H);return function(a){return a.getAttribute("id")===b}}):(delete s.find.ID,s.filter.ID=function(a){var b=a.replace(G,H);return function(a){return(a=typeof a.getAttributeNode!==P&&a.getAttributeNode("id"))&&a.value===b}});s.find.TAG=w.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==P)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,g=b.getElementsByTagName(a);if("*"===a){for(;c=
g[e++];)1===c.nodeType&&d.push(c);return d}return g};s.find.CLASS=w.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==P&&E)return b.getElementsByClassName(a)};O=[];B=[];if(w.qsa=V.test(b.querySelectorAll))g(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&B.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||B.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||B.push(":checked")}),g(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&B.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||B.push(":enabled",":disabled");a.querySelectorAll("*,:x");B.push(",.*:")});(w.matchesSelector=V.test($=F.matches||F.webkitMatchesSelector||F.mozMatchesSelector||F.oMatchesSelector||F.msMatchesSelector))&&
g(function(a){w.disconnectedMatch=$.call(a,"div");$.call(a,"[s!='']:x");O.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});B=B.length&&RegExp(B.join("|"));O=O.length&&RegExp(O.join("|"));
T=(a=V.test(F.compareDocumentPosition))||V.test(F.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ga=a?function(a,c){if(a===c)return S=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!w.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===C&&T(C,a)?-1:c===b||c.ownerDocument===C&&T(C,c)?1:K?N.call(K,a)-N.call(K,c):0:d&4?-1:1}:function(a,c){if(a===c)return S=!0,0;var d,e=0;d=a.parentNode;var g=c.parentNode,k=[a],W=[c];if(!d||!g)return a===b?-1:c===b?1:d?-1:g?1:K?N.call(K,a)-N.call(K,c):0;if(d===g)return l(a,c);for(d=a;d=d.parentNode;)k.unshift(d);for(d=c;d=d.parentNode;)W.unshift(d);for(;k[e]===W[e];)e++;return e?l(k[e],W[e]):k[e]===C?-1:W[e]===
C?1:0};return b};b.matches=function(a,d){return b(a,null,null,d)};b.matchesSelector=function(a,d){(a.ownerDocument||a)!==A&&I(a);d=d.replace(Ba,"='$1']");if(w.matchesSelector&&E&&(!O||!O.test(d))&&(!B||!B.test(d)))try{var e=$.call(a,d);if(e||w.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(g){}return 0<b(d,A,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==A&&I(a);return T(a,b)};b.attr=function(a,b){(a.ownerDocument||a)!==A&&I(a);var c=s.attrHandle[b.toLowerCase()],
c=c&&xa.call(s.attrHandle,b.toLowerCase())?c(a,b,!E):void 0;return void 0!==c?c:w.attributes||!E?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;S=!w.detectDuplicates;K=!w.sortStable&&a.slice(0);a.sort(ga);if(S){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}K=null;return a};Z=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=Z(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=Z(b);return c};s=b.selectors={cacheLength:50,createPseudo:e,match:aa,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(G,H);a[3]=(a[3]||a[4]||a[5]||"").replace(G,H);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(aa.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&Ca.test(c)&&(b=U(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(G,H).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ma[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==P&&a.getAttribute("class")||"")})},ATTR:function(a,d,e){return function(g){g=b.attr(g,a);if(null==g)return"!="===d;if(!d)return!0;g+="";return"="===d?g===e:"!="===d?
g!==e:"^="===d?e&&0===g.indexOf(e):"*="===d?e&&-1<g.indexOf(e):"$="===d?e&&g.slice(-e.length)===e:"~="===d?-1<(" "+g+" ").indexOf(e):"|="===d?g===e||g.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,b,c,d,e){var g="nth"!==a.slice(0,3),k="last"!==a.slice(-4),l="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,f){var h,p,v,u,n;c=g!==k?"nextSibling":"previousSibling";var y=b.parentNode,m=l&&b.nodeName.toLowerCase();f=!f&&!l;if(y){if(g){for(;c;){for(p=b;p=p[c];)if(l?p.nodeName.toLowerCase()===
m:1===p.nodeType)return!1;n=c="only"===a&&!n&&"nextSibling"}return!0}n=[k?y.firstChild:y.lastChild];if(k&&f){f=y[x]||(y[x]={});h=f[a]||[];u=h[0]===D&&h[1];v=h[0]===D&&h[2];for(p=u&&y.childNodes[u];p=++u&&p&&p[c]||(v=u=0)||n.pop();)if(1===p.nodeType&&++v&&p===b){f[a]=[D,u,v];break}}else if(f&&(h=(b[x]||(b[x]={}))[a])&&h[0]===D)v=h[1];else for(;p=++u&&p&&p[c]||(v=u=0)||n.pop();)if((l?p.nodeName.toLowerCase()===m:1===p.nodeType)&&++v)if(f&&((p[x]||(p[x]={}))[a]=[D,v]),p===b)break;v-=e;return v===d||
0===v%d&&0<=v/d}}},PSEUDO:function(a,d){var g,k=s.pseudos[a]||s.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return k[x]?k(d):1<k.length?(g=[a,a,"",d],s.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var c,e=k(a,d),g=e.length;g--;)c=N.call(a,e[g]),a[c]=!(b[c]=e[g])}):function(a){return k(a,0,g)}):k}},pseudos:{not:e(function(a){var b=[],c=[],d=fa(a.replace(X,"$1"));return d[x]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var g=a.length;g--;)if(c=e[g])a[g]=!(b[g]=c)}):
function(a,e,g){b[0]=a;d(b,null,g,c);return!c.pop()}}),has:e(function(a){return function(d){return 0<b(a,d).length}}),contains:e(function(a){a=a.replace(G,H);return function(b){return-1<(b.textContent||b.innerText||Z(b)).indexOf(a)}}),lang:e(function(a){Da.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(G,H).toLowerCase();return function(b){var c;do if(c=E?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===F},focus:function(a){return a===A.activeElement&&(!A.hasFocus||A.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!s.pseudos.empty(a)},header:function(a){return Fa.test(a.nodeName)},input:function(a){return Ea.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:u(function(){return[0]}),
last:u(function(a,b){return[b-1]}),eq:u(function(a,b,c){return[0>c?c+b:c]}),even:u(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:u(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:u(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:u(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};s.pseudos.nth=s.pseudos.eq;for(R in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})s.pseudos[R]=f(R);for(R in{submit:!0,reset:!0})s.pseudos[R]=h(R);n.prototype=s.filters=
s.pseudos;s.setFilters=new n;U=b.tokenize=function(a,d){var e,g,k,l,f,h,p;if(f=na[a+" "])return d?0:f.slice(0);f=a;h=[];for(p=s.preFilter;f;){if(!e||(g=za.exec(f)))g&&(f=f.slice(g[0].length)||f),h.push(k=[]);e=!1;if(g=Aa.exec(f))e=g.shift(),k.push({value:e,type:g[0].replace(X," ")}),f=f.slice(e.length);for(l in s.filter)if((g=aa[l].exec(f))&&(!p[l]||(g=p[l](g))))e=g.shift(),k.push({value:e,type:l,matches:g}),f=f.slice(e.length);if(!e)break}return d?f.length:f?b.error(a):na(a,h).slice(0)};fa=b.compile=
function(a,b){var c,d=[],e=[],g=oa[a+" "];if(!g){b||(b=U(a));for(c=b.length;c--;)g=ea(b[c]),g[x]?d.push(g):e.push(g);g=oa(a,va(e,d));g.selector=a}return g};ja=b.select=function(a,b,c,d){var e,g,k,l,f="function"===typeof a&&a,h=!d&&U(a=f.selector||a);c=c||[];if(1===h.length){g=h[0]=h[0].slice(0);if(2<g.length&&"ID"===(k=g[0]).type&&w.getById&&9===b.nodeType&&E&&s.relative[g[1].type]){if(b=(s.find.ID(k.matches[0].replace(G,H),b)||[])[0])f&&(b=b.parentNode);else return c;a=a.slice(g.shift().value.length)}for(e=
aa.needsContext.test(a)?0:g.length;e--;){k=g[e];if(s.relative[l=k.type])break;if(l=s.find[l])if(d=l(k.matches[0].replace(G,H),ca.test(g[0].type)&&p(b.parentNode)||b)){g.splice(e,1);a=d.length&&m(g);if(!a)return J.apply(c,d),c;break}}}(f||fa(a,h))(d,b,!E,c,ca.test(a)&&p(b.parentNode)||b);return c};w.sortStable=x.split("").sort(ga).join("")===x;w.detectDuplicates=!!S;I();w.sortDetached=g(function(a){return a.compareDocumentPosition(A.createElement("div"))&1});g(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||k("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!w.attributes||!g(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&k("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});g(function(a){return null==a.getAttribute("disabled")})||k("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof r&&r.amd?r(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,b){return this.regexp(b).test(a)},redact:function(a,b){return a.replace(this.regexp(b),"___")},regexp:function(c){c=b.extend({},c);var e=b.map(b.all(a,
function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+e.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,b){return this.contains(a+" "+document.referrer,b||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full"},bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},
ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{ancestor:!1,attributes:["name"],parser:/^Post(\d+)$/,selector:"a[name^='Post']"},scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},
vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},c={getPostId:function(a){var c;b.find(this.spec.attributes||["id"],b.bind(function(b){c=a[b]?a[b].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),
b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];if(this===b.platforms.NONE)return c;!a&&(document&&document.body)&&(a=[document.body]);a&&this.spec&&(c=!1===this.spec.ancestor?b.select(this.spec.selector):b.reduce([],b.withScope(a,this.spec.selector),function(a,b){return a.concat(b[1])}));return c}};b.each(a,function(d,e){d.id=d.id||e;b.each(c,function(a,c){d[c]=b.bind(a,d)});a[e]=d});a.findById=function(a){return b.find(b.platforms,
function(b){return b.id===a})};return a}();b.observer=function(){var a=[],c=0,d=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,g){if(c.document&&b.traits.mutation){var k={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var d=[];"characterData"===a.type?a.target&&(d=[a.target]):a.addedNodes&&a.addedNodes.length&&(d=b.toArray(a.addedNodes));d.length&&(c=c.concat(d))});
0<c.length&&g(c)}))};a.push(k);d(k)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,d)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&
!b.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var h,n,q,t;f={PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],rels:["norewrite"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var e=c[d],g;if(e&&e.callback&&a){if("string"===
b.type(a)&&(g=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(g[1]);"domains"===d&&"array"===b.type(a)&&(a={results:a});e.callback.apply(window,[a].concat(e.data||[]))}})};return function(d){var l={},h={};b.each(d,function(a){a=c.apply(this,a);var d=a.method;l[d]=b.prune(a.params);h[d]={callback:a.opts.fn||b.noop,data:a.data}});e({data:h,method:"batch",params:b.extend(f.commonParams(),{batch:window.JSON.stringify(l)}),opts:{jsonp:!1,fn:function(b,c){a(b,c)}}})}}(),c=function(a,c,e){var p=b.toArray(arguments).slice(3,
arguments.length),v=a,n=d(e),m;m=b.extend(f.commonParams(a),c);m.subId&&m.key!==h.key&&(m.subId=null);return{data:p,method:v,opts:n,params:m}},d=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(d){var e;"object"===b.type(d)&&("array"===b.type(d.crawl)&&"object"===b.type(t.crawler)&&"function"===b.type(t.crawler.crawl))&&(e=b.map(d.crawl,function(a){return a+""}),delete d.crawl,t.crawler.crawl(e));return c.apply(a,arguments)}}(a.fn));return a},e=function(a){return b.request.apply(b,
[h.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,b.batchArgs(arguments)):e(c.apply(this,arguments))},function(){return{batch:h.batch_calls,timeout:h.batch_call_timeout}})}(),addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var g=a.open("",c);g.focus();return g}},c=function(a){var c=a.previousSibling,
g=a.nextSibling,k=["",a.textContent,""],l=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},h=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==k[1]&&(k[0]=c&&3===c.nodeType?l(c,"previous"):
"",k[2]=g&&3===g.nodeType?l(g,"next"):"",k=h.apply(this,k),""!==k[0]&&""!==k[2]&&(k[0]=k[0].split(" ").reverse().slice(0,10+(" "===k[0].substr(k[0].length-1,1)?1:0)).reverse().join(" "),k[2]=k[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:k[0],after:k[2],txt:k[1],loc:location.href,out:b.getActualHref(a),v:2},f.log("info",b.toQuery(a))))};return function(d,e){var g,k,f,p,n=b.context(d)||window;e=d.target||e;e=!e||e===n.name||"_top"===e&&n.top===n||
"_parent"===e&&n.parent===n?"_self":e;f=a(n,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))p="go";else try{if(void 0===f.document)throw!0;p="jsonp"}catch(m){p="go"}g=b.destructing(b.bind(function(){h.time_click&&arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(d,f,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||
!h.enabled)return g();k=this.clickParams(d,p);this.logTime();h.log_context&&c(d);if("go"===p)this.redirect(this.api.now("click",k,{"return":!0}),n,f,e);else if(f===n)this.api.now("click",k,{fn:g,timeout:h.click_timeout});else{if(b.contextIsAncestor(n,f))return this.redirect(b.getActualHref(d),n,f,e);g=b.entryPoint(g);setTimeout(function(){g()},h.click_timeout);f.document.open();f.callback=g;f.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",
k,{fn:"callback","return":!0})+'">\x3c/script></head></html>');f.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:h.reaffiliate||null,title:window.document.title,txt:a.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:h.key?null:h.dr_key,key:h.key,libId:h.library_id};("click"===
a||"ping"===a)&&b.extend(c,{cuid:h.cuid,loc:location.href,subId:h.sub_id,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==h||1E3<b?a(0==h&&l):setTimeout(function(){c(a,2*b)},2*b)}function f(){--h||(l=!p&&n)}var l=!1,h=2,p=!1,n=!1;if("function"==typeof b){a+="?ch=*&rn=*";var m=11*Math.random(),q=new Image;q.onload=f;q.onerror=function(){p=!0;f()};q.src=a.replace(/\*/,1).replace(/\*/,m);q=new Image;q.onload=f;q.onerror=function(){n=
!0;f()};q.src=a.replace(/\*/,2).replace(/\*/,m);c(b,250)}}}}catch(c){a={detect:function(a,b){b(!0)}}}return function(c){var e=b.updateUrl(h.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,c)}}(),enabled:function(){if(h.enabled&&q!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))h.enabled=!1;return h.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!t[a]){var d=t,e;e=c;e="function"===b.type(e)?b.entryPoint(b.bind(e,f)):e;d[a]=e}}}(),fire:function(){var a=
{};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,c){if(h.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,
"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return h.harmony_level<=a}}(),init:function(){var a=function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;n={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(d){}b.exceptionLogger(b.bind(c.logException,c),!h.dev);b.each(h.script_timeout);
return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);t=q[m]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");
this.expose("opt");this.expose("platform");this.expose("registerProcessor",function(){if(0<arguments.length)return f.registerProcessor.apply(f,arguments)});b.extend(t,t===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;h.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",
function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:f.onClick,right:f.onContextmenu},d={left:b.noop,right:b.noop},e=b.traits.windowLevelHandlers?a:a.document,g=function(e){e=e||a.event;if((e=b.eventLink(e))&&!b.cache(e,"evented"))l(e,f.harmony(b.harmony.LINK_LEVEL_EVENTS)?c:d),b.cache(e,"evented",!0)},k=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,
b){return a.concat(b)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&f.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a",{ancestors:!1}),function(a){f.processLinks(a[1])}),b.each(n,function(b,c){f.runPlugin(c,a)}))},function(){return{batch:h.batch_mutation,timeout:h.batch_mutation_timeout}}))},l=function(a,c){b.on(a,"click",b.bind(c.left,f));b.on(a,"contextmenu",b.bind(c.right,f))};if(h.dynamic)b.on("DOMReady",function(){k(a)});b.on(e,"copy",b.bind(f.onCopy,f));b.on(e,"mousedown",
g);if(f.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",g)})});(!b.traits.quirksMode||f.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&l(e,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(t[b[a]]=window[a],"vglnk_domain"===a&&(t[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,
c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){h.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(f);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(m="vglnk");var a=window,b=m.split("."),d;for(m=b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];q=a;
t=q[m]=q[m]||{}},initOptions:function(){var a;this.initLegacyOptions();h=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),h,t,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,
dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,test_agg:!1,time_click:!1,time_ping:!1,testing_js:[],plugins:{crawler:{},link_affiliation:{},modified_clicks:{}}});for(a in h)"_plugin"===a.substr(-7)&&delete h[a]},initPlugins:function(){var a,c=1,d={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},e=["spotlight"],g=function(b){return function(b){return function(){delete n[b].opts.mode;
c=1;clearTimeout(a);l()}}(b)},k=function(a){var c;b.find(d,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:h.key,link_phrases:!1});a[c].link_urls=h.link_urls;return a},l=function(){var d={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},e=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);f.log.apply(this,c)}}},g=function(a){return!Boolean(a._ran)};a=null;b.each(b.all(n,g),function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+
"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,d,a.setup(a.opts,b.clone(b),t,e(h.key))),a["public"]&&f.expose(c,a["public"],!1)),a.opts.mode!==f.PLUGIN_MANUAL&&f.runPlugin(c))});b.find(n,g)&&(a=setTimeout(b.entryPoint(l),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},p=function(){setTimeout(function(){f.api.flush()},100);l();b.on("DOMReady",function(){setTimeout(f.api.flush,0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=d[c]||c;"object"===
typeof a&&!1!==a.enabled&&(n[c]={opts:a},b.contains(e,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,g(c)))},this));p()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(h.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){h.nofollow[a.href]&&
!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var e,g="",f=!1;try{e=c.hostname,g=c.protocol,e.charAt(0)}catch(l){return!0}""!==e&&(e=b.canonicalizeHostname(c));
f=Boolean(""===e||a===e||!g.match(/^https?:$/i)||h.norewrite[e]);g=b.cache(c,"type");c=b.cache(c,"params")||{};if(!Boolean(g||c.type)&&!f)f=Boolean(!h.rewrite_original||"object"===b.type(h.commercial)&&!h.commercial[e]);return f}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var g,f=b.toQuery({libId:h.library_id,nocache:b.uniqid()});g="pixel.gif";if("custom"===a)f+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],function(a){b.each(["e","i",
"o"],function(b){delete a[b]});f+="&"+b.toQuery(a)});else{f+="&"+b.toQuery({key:h.key,drKey:h.key?null:h.dr_key});if("time"===a)g="time.gif",a={time:d,type:c};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;f+="&"+b.toQuery(a)}g=h.api_url+"/"+g+"?"+f;b.pii.transmits(g)||(b.createEl("img").src=g)},logException:function(a){if(h.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",
a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,d,e,g){var f=e||b.getActualHref(a),l=b.bind(function(){this.redirect(f,b.context(a),c,d)},this);"object"===typeof g&&(g.tracking||g.image)?(e=b.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.entryPoint(l),g.timeout||h.hop_timeout)):
l()},onApiPing:function(a,c,d,e,g,k){h.rewrite_original=!1;g=b.reformatKeys(g||{});var l,p;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};p=b.extend(h.plugins,g.plugins);h=b.extend(h,g);delete h.plugins;h.library_id=a;h.click_timeout=c;h.time_ping&&this.logTime("png");h.test_agg&&(h.harmony_level=b.harmony.LINK_LEVEL_EVENTS);"array"===b.type(h.testing_js)&&0<h.testing_js.length&&b.each(h.testing_js,function(a){b.jsonp(a)});b.extend(h.norewrite,
e(d));b.extend(h.nofollow,e(k));for(l in h)"on"===l.toLowerCase().substr(0,2)&&(2<l.length&&"function"===b.type(h[l]))&&(b.on(f,l.toLowerCase().substr(2),b.bind(h[l],window)),delete h[l]);this.initPlugins(p);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=b.eventLink(a);if(e&&this.isRewritable(e)&&!c&&d&&!b.isDefaultPrevented(a))return this.click(e),b.preventDefault(a)},onContextmenu:function(a){(a=
b.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var c,d,e,g=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(k){}0<e.length&&128>=e.length&&g.push(e)}}b.each(g,function(a){f.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(h[a]=
b);return h[a]},ping:function(){var a=!1;return function(){if(!a&&(h.key||h.dr_key)){var c={ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(h.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(h.platform)||b.platforms.NONE},processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,
"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a}},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){c=c||window.top;!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.entryPoint(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,
d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},runPlugin:function(a,c){var d=window.document,e=n[a];if(e&&e.initDocuments){if(c)e.initNodes(c);else if(e.init(),"function"===b.type(e.initDocuments)&&"document"===b.type(d)&&e.initDocuments([d]),"function"===b.type(e.initNodes)&&"element"===b.type(d.body))b.on("DOMReady",function(){e.initNodes([d.body])});e._ran=!0}},
registerProcessor:function(){var a=!1,c=[],d=function(d){if(void 0===d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};f.init();try{delete window.vglnk_self}catch(p){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(m,f,b){var r={},h;m=f.extend({any:!0},m);h={getDomains:function(){var n=[];f.each(r,function(b,f){n.push(f)});0<n.length&&b.api("domains",{domains:n.join("|")},{fn:f.bind(h.onDomainApi,h)})},init:function(){b.opt("rewrite_original",!0);m.any||b.registerProcessor(f.bind(function(b){this.initDomainLookup();this.saveDomain(b)},this))},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,f.on("DOMReady",f.bind(this.getDomains,this)))}}(),onDomainApi:function(h){var m;
"object"===f.type(h)&&"array"===f.type(h.results)&&(m={},f.each(h.results,function(b){m[b]=!0}),b.opt("commercial",m))},saveDomain:function(b){b=f.canonicalizeHostname(b);r[b]=!0}};return{init:f.bind(h.init,h)}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(m,f,b){var r=[],h=b.platform();m={crawl:function(b){if(h&&!("array"!==f.type(b)||0===b.length))b=f.all(b,function(b){return!f.contains(r,b)}),b=this.findPostsById(b),f.each(b,f.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=f.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return f.all(f.map(h.getPosts(),function(b){return{el:b,id:h.getPostId(b)}}),
function(h){return f.contains(b,h.id)})},processPosts:function(m){m=f.map(m,function(b){r.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:f.toJSON({ct:m,pt:h.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return f.pii.redact(b)}};return{"public":{crawl:f.bind(m.crawl,m)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(m,f,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(m,f,b){m=f.extend({key:null},m);var r={init:function(b){f.each(this.getDRSearchForms(b),function(b){if(!f.cache(b,"evented")){var h=r.getInput(b),m=function(){h.value||f.css(h,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(b,"evented",!0);b.onsubmit=null;h.onfocus=null;h.onblur=null;f.on(h,"focus",function(){f.css(h,{"background-image":"none"})});f.on(h,"blur",m);m();f.on(b,"submit",function(f){r.onSubmit(f,b)})}})},
getDRSearchForms:function(b){var m=[];f.each(b,function(b){"element"===f.type(b)&&f.each(b.getElementsByTagName("form"),function(b){r.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&m.push(b)})});return m},getInput:function(b){return b.p||b.q2},onSubmit:function(h,n){h=h||window.event;var q="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:r.getInput(n).value}),q=f.createA(q,"_blank");f.cache(q,"params",{key:m.key});b.click(q);return f.preventDefault(h)}};if(m.key)return{init:f.bind(r.init,r),
initNodes:function(b){r.init(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(m,f,b,r){var h,n=b.platform(),q=0;h={cache:function(){var b={};return function(f,a){if(1>=arguments.length){var c;c=f?b[f]:b;return c}if(2===arguments.length)return b[f]=a,!0}}(),cached:f.noop,getLinks:function(m,p){b.api("optimize",{i:p?p.join("|"):null,pt:n.id,u:location.href},{fn:f.bind(h.onOptimizeApi,h)},m,p)},loadOptimizations:function(h){f.each(h,f.bind(function(b,a){this.cache(a,b)},this));b.registerProcessor(f.bind(this.optimizeLink,this));this.log()},
log:f.batchable(function(){r("optimize",{ct:q});q=0},function(){return{timeout:1E3}}),onOptimizeApi:function(b,h,a){"object"===f.type(b)&&"object"===f.type(b.optLinks)&&this.loadOptimizations(b.optLinks,h,a)},optimizeLink:function(){var b=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(a,b){if(b)return Boolean(f.cache(a,"type"))}}),h=function(a){var b=a.href,d=a.textContent||a.innerText,e=function(){var b=f.canonicalizeHostname(a);return f.canonicalizeHostname(f.createEl("a",
{href:d}))===b},g=function(){var b;return e()?(b=f.fromQuery(a.search),f.find(b,function(a){return a===d})):!1};return{exact:b===d||function(){var a=d.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+f.map(a,f.escapeRegExp).join(".+")+"$").test(b)}()||g(),partial:function(){var b=f.canonicalizeHostname(a);return RegExp("\\b"+f.escapeRegExp(b)+"\\b","i").test(d)}()||-1!==d.indexOf(b)}};return function(a){var c,d=this.cache(a.href);if(d&&b(a)){c=h(a);if(c.exact){c=d.frdLink||d.optLink;for(var e;e=
a.firstChild;)a.removeChild(e);a.appendChild(document.createTextNode(c))}else if(c.partial)return;f.cache(a,"params",{type:"LO",origOutId:d.pcid+":"+d.linkId});a.href=d.optLink;q++}}}()};return{initNodes:function(b){var f;b.length&&(f=n.getPostIds(b),h.cached(f)?h.optimizeLinks(b,f):h.getLinks(b,f))}}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(m,f,b){m=f.extend({level:null},m);return{init:function(){var f=parseInt(m.level,10);isFinite(f)&&b.opt("harmony_level",f)}}};
window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(m,f,b,r){var h,n,q,t=null;m=f.extend({cat:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},m);if(m.key)return h=b.platform(),n={cache:function(){var b={},a={},c=function(c,d){var k={};"array"===f.type(d)&&0<d.length&&f.find(d,function(b){if(a[b]){k._post_is_cached=!0;if(c)return k[c]=a[b][c],!0;f.each(a[b],function(a,b){k[b]||(k[b]=a)})}});k=f.extend(f.clone(b),k);
return c?k[c]:k},d=function(c,d,k){(k="array"===f.type(k)&&0<k.length?k:null)&&f.each(k,function(b){a[b]=a[b]||{};"L"!==d.type&&(a[b][c]=d)});if(!k||"L"===d.type)b[c]||(b[c]=d);return!0};return function(a,b,k){var l=f.all(f.toArray(arguments),function(a){return Boolean(a)});"array"===f.type(l[l.length-1])&&(k=l.pop());a=l[0];b=l[1];if(1>=l.length)return c(a,k);if(2===l.length)return d(a,b,k)}}(),cached:function(){var b=function(a){var b=n.cache(a);return"array"===f.type(a)&&a.length?b._post_is_cached:
Boolean(f.find(b,function(){return!0}))};return function(a){return!a||"array"!==f.type(a)?b(a):f.all(a,function(a){return b([a])}).length===a.length}}(),focusLink:function(b){b.id||(b.id=f.uniqid("vl-link-"));location.href.hash="#"+b.id;window.scrollBy(0,-150)},getPartnerParams:function(){var f,a,c=b.opt("partner"),d={};for(f in c)break;if(f)for(a in c[f])d[f+"_"+a]=c[f][a];return d},getPhrases:function(p,a){b.api("insert",f.extend(n.getPartnerParams(),{cat:m.cat,i:a?a.join("|"):null,mode:m.mode,
pt:h.id,ps:m.product_source,u:location.href,type:m.type}),{fn:f.bind(n.onInsertApi,n)},p,a)},init:function(){m.scope=m.scope||h.scope;m.link_urls&&(q=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"))},initLink:function(h,a,c){if(c=m.link_target||
c)h.target=c;h.href||(h.href=a.url);h.rel="nofollow";f.cache(h,"params",{exp:t,key:m.key,mid:a.mid,type:a.type||null});f.cache(h,"href",h.href);b.link(h)},insertLinks:function(){var b,a=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a")&&Boolean(a.href)}}),c=function(b,e,f,g){if(a(e,{ancestors:!Boolean(g),
self:!0}))if(3===e.nodeType)d(b,e,f);else if(1===e.nodeType)for(e=e.firstChild;e;)g=e.nextSibling,c(b,e,f,!0),e=g},d=function(a,b,c){var d=!1,f=b.parentNode,g=function(a,b){f.insertBefore(a,b);f.removeChild(b)};b.data&&(d=a.test(b.data.replace(/\s+/," ")));d&&e(a,b,c,g)},e=function(a,c,d,e){for(var h,q,t,r,sa=function(a){var c;a=!a||!m.per_phrase||!b[a.phrase]||b[a.phrase].count<m.per_phrase;c=!m.per_page||f.reduce(0,b,function(a,b){return a+b.count})<m.per_page;return a&&c},ua=function(a,b,c){var d,
e,g;if(!c.phrase)return!0;e=f.createEl("span");b.parentNode.insertBefore(e,b);e.appendChild(b);g=f.geometry(e);(m.proximity||m.same_proximity)&&f.find(n.cache(a),function(a){var b,e;if(a.links){if((b=n.normalizePhrase(a.phrase)===n.normalizePhrase(c.phrase))&&!m.same_proximity||!b&&!m.proximity)return!1;e=b?Math.max(m.same_proximity,m.proximity):m.proximity;a.links=f.all(a.links,function(a){var b=f.isInDom(a.el);!d&&b&&(d=f.find(a.segments,function(a){a=a.geometry;a=f.extend({},a);a.x1-=e;a.y1-=e;
a.x2+=e;a.y2+=e;if(a.x1<g.x2&&a.x2>g.x1&&a.y1<g.y2&&a.y2>g.y1)return!0}));return b});return d}});return function(a){e.parentNode.insertBefore(b,e);e.parentNode.removeChild(e);return a}(!d)},Q=function(a,b){var c,d,e,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===g||e.offsetTop===g.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),g=e;l.geometry=f.geometry.apply(f,l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};c&&
c.data&&""!==c.data&&(Boolean(t=c.data.match(/^\s+/))||Boolean(t=c.data.match(a)));)q=t[0],r=t.slice(1).join(""),h=(h=n.normalizePhrase(r))?n.cache(h,d):null,q=c.data.indexOf(q)+q.length-r.length,0<q&&(c=c.splitText(q)),q=c.length<=r.length?null:c.splitText(r.length),r&&!h&&(h={url:r.match(/^https?:\/\//i)?r:"http://"+r,type:"U"}),h&&(h.url.match(/https?:\/\//i)&&r&&sa(h)&&ua(d,c,h))&&(r=g(r,h),f.cache(r,"unlinked")||(e(r,c),Q(r,h),c=h.phrase||h.url,b[c]=b[c]||{count:0,phrase:h.phrase,type:h.type},
b[c].count++)),c=q},g=function(a,b){var c;c=f.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";f.cache(c,"type","inserted");f.cache(c,"phrase",a);m.ui&&"U"!==b.type&&(c.title="Link added by VigLink");n.initLink(c,b);return c};return function(d,e){var g=n.regexp(e);b={};g&&(f.each(f.all(d,a),function(a){c(g,a,e)}),m.link_phrases&&n.log(b))}}(),loadPhrases:function(b,a,c){f.each(b,function(a){a.phrase&&a.url&&(a.phrase=n.normalizePhrase(a.phrase),
n.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},c))});this.insertLinks(a,c)},log:function(b){var a,c=0,d=0,e=0,g=[],h=[],e=function(a,b){return b.split(",")[0]-a.split(",")[0]};f.each(b,function(b,e){var f=parseInt(b.count,10);0<f&&(a=[f,e.replace(/\|/g,"%7C")].join(),"L"===b.type?(c++,h.push(a)):"U"!==b.type&&(d++,g.push(a)))});h.sort(e);g.sort(e);e=c+d;0<e&&r("insert",[{ct:e,cl:c,ch:d,cu:0,exp:t},{pl:h.join("|")},{ph:g.join("|")}])},normalizePhrase:function(b){return b.toLowerCase().replace(/(^\s+|\s+$)/g,
"").split(/\s+/).join(" ")},onInsertApi:function(b,a,c){"object"===f.type(b)&&(t=b.exp,b.results&&this.loadPhrases(b.results,a,c))},regexp:function(b){var a;b=n.cache(b);delete b._post_is_cached;b=f.map(b,function(a,b){return f.escapeRegExp(b).split(" ").join("\\s+")});0<b.length&&(a="(?:^|[\\s\"'\\(])("+b.join("|")+")(?=\\s|\\W*$|\\W{2})",a=RegExp(q?"(?:"+a+"|"+q.source+")":a,"i"));return a||q}},{init:f.bind(n.init,n),initNodes:function(b){var a;m.scope&&(b=f.reduce([],f.withScope(b,m.scope),function(a,
b){return a.concat(b[1])}));b.length&&(a=h.getPostIds(b),m.link_phrases&&!n.cached(a)?n.getPhrases(b,a):n.insertLinks(b,a))}}};
